# =============================================================================
# roles/k8s_nfs_provisioner/defaults/main.yml
# =============================================================================

---
nfs_server_ip:    "10.10.0.42"
nfs_export_path:  "/exports/k8s"
storage_class:    "nfs"
helm_version:     "v3.17.3"
