# =============================================================================
# roles/loki/handlers/main.yml
# =============================================================================

---
- name: Restart Loki
  ansible.builtin.systemd:
    name: loki
    state: restarted
    daemon_reload: true
